-- =========================================================================
-- mig 284 · LAS PROMOCIONES DEL PROVEEDOR (#908)
--
-- Algunos proveedores liquidan una promocion ("comprando X, bonificacion de
-- $Y por bulto") y NO la descuentan en la factura: la acreditan despues. Si
-- quien carga la compra no se acuerda de agregar el cargo negativo
-- "Bonificacion" con su alcance, el costo queda inflado sin ningun aviso.
--
-- Esta migracion solo agrega DONDE se declara la promo del proveedor. La
-- deteccion es del modal de compra (src/utils/sugerenciasBonificacion.ts): con
-- las promos vigentes del proveedor a la fecha de la factura calcula lo que se
-- tendria que haber descontado, lo compara contra lo que ya descontaron las
-- lineas y los cargos negativos, y SUGIERE el cargo. Nunca lo aplica solo.
-- Por eso no hay funciones ni cambios en las RPCs de compra: aceptar una
-- sugerencia arma un cargo como cualquier otro.
--
--   * `promociones_proveedor`: una fila por promo y por FICHA de proveedor.
--     Los proveedores son por sucursal (dos fichas del mismo proveedor en dos
--     sucursales son dos filas de `proveedores`), asi que la promo tambien:
--     FK compuesta (proveedor_id, sucursal_id). Dos tipos:
--       - 'monto_por_unidad': importe fijo SIN IVA por unidad de la linea de
--         compra (por bulto, si el producto se compra por bulto).
--       - 'porcentaje': % sobre el neto de la linea (ya bonificada).
--     Vigencia por fecha de factura, ambos extremos inclusive y opcionales.
--   * `promocion_proveedor_productos`: el alcance. FK compuesta a productos
--     (id, sucursal_id): una promo de una sucursal no puede colgar productos
--     de otra.
--
-- No es `promociones` (las de venta): esas regalan unidades al cliente y
-- tienen reglas, acumuladores y ajuste de stock. Esto es un acuerdo de compra
-- con el proveedor, y mezclarlo ahi obligaria a cada consumidor de
-- `promociones` a filtrar las de compra.
--
-- `updated_at` lo escribe el cliente al editar (sin trigger: no hace falta
-- una funcion nueva para un dato informativo).
--
-- RLS: el patron de compras/proveedores. Leer: quien carga compras (admin,
-- encargado, deposito, como producto_medidas de la 278) y de la sucursal
-- activa, porque el modal de compra las necesita. Escribir: admin y de la
-- sucursal activa, como la ficha del proveedor (mt_proveedores_*), porque es
-- un acuerdo comercial. anon: nada.
-- =========================================================================

BEGIN;

-- -------------------------------------------------------------------------
-- 1 · Promociones
-- -------------------------------------------------------------------------
CREATE TABLE public.promociones_proveedor (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id       bigint NOT NULL REFERENCES public.sucursales(id),
  proveedor_id      bigint NOT NULL,
  nombre            text NOT NULL,
  tipo              text NOT NULL,
  -- SIN IVA, como el monto de un cargo. El tope descarta NaN e infinito (en
  -- numeric, NaN es MAYOR que todo y pasaria un `> 0` pelado).
  monto_por_unidad  numeric(14,4),
  porcentaje        numeric(7,4),
  vigente_desde     date,
  vigente_hasta     date,
  activo            boolean NOT NULL DEFAULT true,
  notas             text,
  created_by        uuid DEFAULT auth.uid(),
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT promociones_proveedor_nombre_ck CHECK (btrim(nombre) <> ''),
  CONSTRAINT promociones_proveedor_tipo_ck CHECK (tipo IN ('monto_por_unidad', 'porcentaje')),
  -- Un tipo, un numero: el otro va vacio, no en 0 "por las dudas".
  CONSTRAINT promociones_proveedor_valor_ck CHECK (
    (tipo = 'monto_por_unidad'
       AND monto_por_unidad IS NOT NULL AND monto_por_unidad > 0 AND monto_por_unidad < 1000000000
       AND porcentaje IS NULL)
    OR
    (tipo = 'porcentaje'
       AND porcentaje IS NOT NULL AND porcentaje > 0 AND porcentaje <= 100
       AND monto_por_unidad IS NULL)
  ),
  CONSTRAINT promociones_proveedor_vigencia_ck CHECK (
    vigente_desde IS NULL OR vigente_hasta IS NULL OR vigente_hasta >= vigente_desde),
  -- Compuesta: el aislamiento por sucursal (migs 186/187). Una simple dejaria
  -- colgar una promo de una sucursal de la ficha del proveedor en otra.
  CONSTRAINT promociones_proveedor_proveedor_fk FOREIGN KEY (proveedor_id, sucursal_id)
    REFERENCES public.proveedores(id, sucursal_id) ON DELETE CASCADE,
  -- Para que el alcance pueda apuntar con FK compuesta.
  CONSTRAINT promociones_proveedor_id_sucursal_uk UNIQUE (id, sucursal_id)
);

CREATE INDEX promociones_proveedor_proveedor_idx
  ON public.promociones_proveedor (sucursal_id, proveedor_id);

COMMENT ON TABLE public.promociones_proveedor IS
  'Promociones de compra declaradas por proveedor y sucursal (#908). El modal de compra las usa para SUGERIR la bonificacion que la factura no desconto, nunca la aplica sola.';
COMMENT ON COLUMN public.promociones_proveedor.monto_por_unidad IS
  'Tipo monto_por_unidad: importe SIN IVA por unidad de la linea de compra.';
COMMENT ON COLUMN public.promociones_proveedor.porcentaje IS
  'Tipo porcentaje: % sobre el neto de la linea ya bonificada.';

-- -------------------------------------------------------------------------
-- 2 · Alcance
-- -------------------------------------------------------------------------
CREATE TABLE public.promocion_proveedor_productos (
  promocion_id  bigint NOT NULL,
  sucursal_id   bigint NOT NULL,
  producto_id   bigint NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT promocion_proveedor_productos_pkey PRIMARY KEY (promocion_id, producto_id),
  CONSTRAINT promocion_proveedor_productos_promo_fk FOREIGN KEY (promocion_id, sucursal_id)
    REFERENCES public.promociones_proveedor(id, sucursal_id) ON DELETE CASCADE,
  CONSTRAINT promocion_proveedor_productos_producto_fk FOREIGN KEY (producto_id, sucursal_id)
    REFERENCES public.productos(id, sucursal_id) ON DELETE CASCADE
);

CREATE INDEX promocion_proveedor_productos_producto_idx
  ON public.promocion_proveedor_productos (producto_id, sucursal_id);
CREATE INDEX promocion_proveedor_productos_sucursal_idx
  ON public.promocion_proveedor_productos (sucursal_id, promocion_id);

COMMENT ON TABLE public.promocion_proveedor_productos IS
  'Productos alcanzados por una promocion de proveedor (#908). Misma sucursal que la promo, por FK compuesta.';

-- -------------------------------------------------------------------------
-- 3 · RLS y permisos
-- -------------------------------------------------------------------------
ALTER TABLE public.promociones_proveedor ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promocion_proveedor_productos ENABLE ROW LEVEL SECURITY;

CREATE POLICY promociones_proveedor_select ON public.promociones_proveedor
  FOR SELECT TO authenticated USING (
    (public.es_admin() OR EXISTS (SELECT 1 FROM public.perfiles WHERE perfiles.id = auth.uid() AND perfiles.rol IN ('encargado', 'deposito')))
    AND sucursal_id = public.current_sucursal_id());
CREATE POLICY promociones_proveedor_insert ON public.promociones_proveedor
  FOR INSERT TO authenticated WITH CHECK (public.es_admin() AND sucursal_id = public.current_sucursal_id());
CREATE POLICY promociones_proveedor_update ON public.promociones_proveedor
  FOR UPDATE TO authenticated
  USING (public.es_admin() AND sucursal_id = public.current_sucursal_id())
  WITH CHECK (public.es_admin() AND sucursal_id = public.current_sucursal_id());
CREATE POLICY promociones_proveedor_delete ON public.promociones_proveedor
  FOR DELETE TO authenticated USING (public.es_admin() AND sucursal_id = public.current_sucursal_id());

CREATE POLICY promocion_proveedor_productos_select ON public.promocion_proveedor_productos
  FOR SELECT TO authenticated USING (
    (public.es_admin() OR EXISTS (SELECT 1 FROM public.perfiles WHERE perfiles.id = auth.uid() AND perfiles.rol IN ('encargado', 'deposito')))
    AND sucursal_id = public.current_sucursal_id());
CREATE POLICY promocion_proveedor_productos_insert ON public.promocion_proveedor_productos
  FOR INSERT TO authenticated WITH CHECK (public.es_admin() AND sucursal_id = public.current_sucursal_id());
CREATE POLICY promocion_proveedor_productos_update ON public.promocion_proveedor_productos
  FOR UPDATE TO authenticated
  USING (public.es_admin() AND sucursal_id = public.current_sucursal_id())
  WITH CHECK (public.es_admin() AND sucursal_id = public.current_sucursal_id());
CREATE POLICY promocion_proveedor_productos_delete ON public.promocion_proveedor_productos
  FOR DELETE TO authenticated USING (public.es_admin() AND sucursal_id = public.current_sucursal_id());

REVOKE ALL ON public.promociones_proveedor FROM anon;
REVOKE ALL ON public.promocion_proveedor_productos FROM anon;

-- -------------------------------------------------------------------------
-- 4 · Verificacion estructural
-- -------------------------------------------------------------------------
DO $verif$
DECLARE
  v_n integer;
BEGIN
  SELECT count(*) INTO v_n FROM pg_class
   WHERE oid IN ('public.promociones_proveedor'::regclass, 'public.promocion_proveedor_productos'::regclass)
     AND relrowsecurity;
  IF v_n <> 2 THEN RAISE EXCEPTION 'mig284: RLS apagada en alguna tabla nueva'; END IF;

  IF has_table_privilege('anon', 'public.promociones_proveedor', 'SELECT')
     OR has_table_privilege('anon', 'public.promociones_proveedor', 'INSERT')
     OR has_table_privilege('anon', 'public.promocion_proveedor_productos', 'SELECT')
     OR has_table_privilege('anon', 'public.promocion_proveedor_productos', 'INSERT') THEN
    RAISE EXCEPTION 'mig284: anon conserva privilegios sobre las tablas nuevas';
  END IF;

  -- Las tres FKs que importan son compuestas.
  SELECT count(*) INTO v_n FROM pg_constraint
   WHERE contype = 'f' AND array_length(conkey, 1) = 2
     AND conname IN ('promociones_proveedor_proveedor_fk',
                     'promocion_proveedor_productos_promo_fk',
                     'promocion_proveedor_productos_producto_fk');
  IF v_n <> 3 THEN RAISE EXCEPTION 'mig284: se esperaban 3 FKs compuestas y hay %', v_n; END IF;
END
$verif$;

-- -------------------------------------------------------------------------
-- 5 · Ensayo funcional. Corre dentro de una subtransaccion que se revierte
--     siempre (RAISE al final): no deja filas. Si una expectativa falla, la
--     migracion entera falla.
-- -------------------------------------------------------------------------
DO $ensayo$
DECLARE
  v_suc        bigint;
  v_prov       bigint;
  v_prod       bigint;
  v_prod_otro  bigint;
  v_prov_otro  bigint;
  v_promo      bigint;
  v_fallas     text := '';
  v_notas      text := '';
  v_cons       text;
BEGIN
  -- Una sucursal con al menos un proveedor y un producto.
  SELECT pv.sucursal_id, pv.id, pr.id INTO v_suc, v_prov, v_prod
    FROM proveedores pv
    JOIN productos pr ON pr.sucursal_id = pv.sucursal_id
   ORDER BY pv.sucursal_id, pv.id, pr.id
   LIMIT 1;
  IF v_suc IS NULL THEN
    RAISE EXCEPTION 'mig284: no hay ninguna sucursal con proveedor y producto; el ensayo no puede correr.';
  END IF;
  -- Producto y proveedor de OTRA sucursal (puede no haber: se informa).
  SELECT id INTO v_prod_otro FROM productos WHERE sucursal_id <> v_suc ORDER BY id LIMIT 1;
  SELECT id INTO v_prov_otro FROM proveedores WHERE sucursal_id <> v_suc ORDER BY id LIMIT 1;

  BEGIN
    -- a · Alta valida, con su alcance.
    INSERT INTO promociones_proveedor (sucursal_id, proveedor_id, nombre, tipo, monto_por_unidad, vigente_desde, vigente_hasta)
      VALUES (v_suc, v_prov, 'ZZZ mig284', 'monto_por_unidad', 150, current_date - 30, current_date + 30)
      RETURNING id INTO v_promo;
    INSERT INTO promocion_proveedor_productos (promocion_id, sucursal_id, producto_id)
      VALUES (v_promo, v_suc, v_prod);
    v_notas := v_notas || 'a alta ok · ';

    -- b · Producto de otra sucursal: lo rechaza la FK compuesta a productos.
    IF v_prod_otro IS NOT NULL THEN
      BEGIN
        INSERT INTO promocion_proveedor_productos (promocion_id, sucursal_id, producto_id)
          VALUES (v_promo, v_suc, v_prod_otro);
        v_fallas := v_fallas || ' [b: producto de otra sucursal entro]';
      EXCEPTION WHEN foreign_key_violation THEN
        GET STACKED DIAGNOSTICS v_cons = CONSTRAINT_NAME;
        IF v_cons <> 'promocion_proveedor_productos_producto_fk' THEN
          v_fallas := v_fallas || format(' [b: rechazo otra FK: %s]', v_cons);
        END IF;
        v_notas := v_notas || 'b producto cruzado rechazado · ';
      END;

      -- c · El alcance con la sucursal del producto ajeno: ahora lo rechaza
      --     la FK compuesta a la promo (la promo es de otra sucursal).
      BEGIN
        INSERT INTO promocion_proveedor_productos (promocion_id, sucursal_id, producto_id)
          VALUES (v_promo, (SELECT sucursal_id FROM productos WHERE id = v_prod_otro), v_prod_otro);
        v_fallas := v_fallas || ' [c: alcance con sucursal ajena entro]';
      EXCEPTION WHEN foreign_key_violation THEN
        GET STACKED DIAGNOSTICS v_cons = CONSTRAINT_NAME;
        IF v_cons <> 'promocion_proveedor_productos_promo_fk' THEN
          v_fallas := v_fallas || format(' [c: rechazo otra FK: %s]', v_cons);
        END IF;
        v_notas := v_notas || 'c promo cruzada rechazada · ';
      END;
    ELSE
      v_notas := v_notas || 'b/c sin otra sucursal con productos · ';
    END IF;

    -- d · Promo con un proveedor de otra sucursal.
    IF v_prov_otro IS NOT NULL THEN
      BEGIN
        INSERT INTO promociones_proveedor (sucursal_id, proveedor_id, nombre, tipo, porcentaje)
          VALUES (v_suc, v_prov_otro, 'ZZZ mig284 cruzada', 'porcentaje', 5);
        v_fallas := v_fallas || ' [d: proveedor de otra sucursal entro]';
      EXCEPTION WHEN foreign_key_violation THEN
        GET STACKED DIAGNOSTICS v_cons = CONSTRAINT_NAME;
        IF v_cons <> 'promociones_proveedor_proveedor_fk' THEN
          v_fallas := v_fallas || format(' [d: rechazo otra FK: %s]', v_cons);
        END IF;
        v_notas := v_notas || 'd proveedor cruzado rechazado · ';
      END;
    ELSE
      v_notas := v_notas || 'd sin otra sucursal con proveedores · ';
    END IF;

    -- e · Coherencia tipo/valor: porcentaje con monto, monto en 0, NaN.
    BEGIN
      INSERT INTO promociones_proveedor (sucursal_id, proveedor_id, nombre, tipo, porcentaje, monto_por_unidad)
        VALUES (v_suc, v_prov, 'ZZZ mig284 e1', 'porcentaje', 5, 10);
      v_fallas := v_fallas || ' [e1: porcentaje con monto entro]';
    EXCEPTION WHEN check_violation THEN
      v_notas := v_notas || 'e1 ok · ';
    END;
    BEGIN
      INSERT INTO promociones_proveedor (sucursal_id, proveedor_id, nombre, tipo, monto_por_unidad)
        VALUES (v_suc, v_prov, 'ZZZ mig284 e2', 'monto_por_unidad', 0);
      v_fallas := v_fallas || ' [e2: monto 0 entro]';
    EXCEPTION WHEN check_violation THEN
      v_notas := v_notas || 'e2 ok · ';
    END;
    BEGIN
      INSERT INTO promociones_proveedor (sucursal_id, proveedor_id, nombre, tipo, monto_por_unidad)
        VALUES (v_suc, v_prov, 'ZZZ mig284 e3', 'monto_por_unidad', 'NaN');
      v_fallas := v_fallas || ' [e3: NaN entro]';
    EXCEPTION WHEN check_violation THEN
      v_notas := v_notas || 'e3 ok · ';
    END;

    -- f · Vigencia invertida.
    BEGIN
      INSERT INTO promociones_proveedor (sucursal_id, proveedor_id, nombre, tipo, porcentaje, vigente_desde, vigente_hasta)
        VALUES (v_suc, v_prov, 'ZZZ mig284 f', 'porcentaje', 3, current_date, current_date - 1);
      v_fallas := v_fallas || ' [f: vigencia invertida entro]';
    EXCEPTION WHEN check_violation THEN
      v_notas := v_notas || 'f ok · ';
    END;

    -- g · Borrar la promo borra su alcance.
    DELETE FROM promociones_proveedor WHERE id = v_promo;
    IF EXISTS (SELECT 1 FROM promocion_proveedor_productos WHERE promocion_id = v_promo) THEN
      v_fallas := v_fallas || ' [g: el alcance sobrevivio al borrado]';
    ELSE
      v_notas := v_notas || 'g cascada ok';
    END IF;

    RAISE EXCEPTION 'mig284_rollback_del_ensayo';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'mig284_rollback_del_ensayo' THEN
      RAISE EXCEPTION 'mig284 · el ensayo funcional exploto: %', SQLERRM;
    END IF;
  END;

  IF v_fallas <> '' THEN
    RAISE EXCEPTION 'mig284 · el ensayo funcional encontro:%', v_fallas;
  END IF;
  IF EXISTS (SELECT 1 FROM promociones_proveedor WHERE nombre LIKE 'ZZZ mig284%') THEN
    RAISE EXCEPTION 'mig284 · el ensayo dejo filas';
  END IF;
  PERFORM set_config('mig284.ensayo', v_notas, true);
  RAISE NOTICE 'mig284 · ensayo funcional OK: %', v_notas;
END
$ensayo$;

COMMIT;
