// Re-export all hooks from modular files
export { supabase, setErrorNotifier, notifyError } from './base'
export { AuthProvider, useAuth } from './useAuth'
export { useProductos } from './useProductos'
export { useBackup } from './useBackup'
export { usePagos } from './usePagos'
export { useFichaCliente } from './useFichaCliente'
export { useReportesFinancieros } from './useReportesFinancieros'
export { useRecorridos } from './useRecorridos'
export { useRendiciones } from './useRendiciones'
export { useSalvedades } from './useSalvedades'
