// Re-export all hooks from modular files
export { supabase, setErrorNotifier, notifyError } from './base'
export { AuthProvider, useAuth } from './useAuth'
export { useClientes } from './useClientes'
export { useProductos } from './useProductos'
export { usePedidos } from './usePedidos'
export { useUsuarios } from './useUsuarios'
export { useDashboard } from './useDashboard'
export { useBackup } from './useBackup'
export { usePagos } from './usePagos'
export { useFichaCliente } from './useFichaCliente'
export { useReportesFinancieros } from './useReportesFinancieros'
export { useMermas } from './useMermas'
export { useCompras } from './useCompras'
export { useRecorridos } from './useRecorridos'
export { useRendiciones } from './useRendiciones'
export { useSalvedades } from './useSalvedades'
